### PR TITLE
Only use - backports-datetime-fromisoformat >=2.0.0,<3.0.0  # [py<311]

### PR DESCRIPTION
**Pull request by kmuehlbauer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kmuehlbauer** [comment]
Gnarf, currently the Python 3.11 envs are broken due to this.

@conda-forge-admin, please rerender

**Comment by kmuehlbauer** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@kmuehlbauer, this would require us dropping `noarch: python`.  It is also not consistent with the upstream repo.  So it would need to be changed there first.  But I think we really don't want to move away from `noarch: python` unless we absolutely have to.  I don't know of a a way to avoid building a separate package for each OS and python version when we do that, so the number of builds goes from 1 to 20 (assuming all 5 architectures and all 4 python versions are supported).

**Comment by kmuehlbauer** [comment]
I'm stuck with 0.56.2 at Python 3.11 since backports-datetime-fromisoformat works only for python versions < 3.11:

```
Encountered problems while solving:
  - package wetterdienst-0.60.0-pyhd8ed1ab_0 requires backports-datetime-fromisoformat >=2.0.0,<3.0.0, but none of the providers can be installed

The environment can't be solved, aborting the operation
```

And 0.56.2 is only installable with `--no-deps` to not downgrade pandas etc.

The strict pinning throughout the dependencies is becoming a major pain point to use wetterdienst on conda-forge in a user-friendly fashion.

**Comment by kmuehlbauer** [comment]
@xylar I totally agree here to not move to noarch. But we would need some workaround to at least get this installed somehow.

**Comment by xylar** [comment]
@kmuehlbauer, I see.  That's a problem.  Let's try to fix it at:
https://github.com/conda-forge/backports-datetime-fromisoformat-feedstock/issues/11

**Comment by kmuehlbauer** [comment]
Thanks @xylar! That's the minimum intrusive action to take.

**Comment by xylar** [comment]
I think https://github.com/conda-forge/backports-datetime-fromisoformat-feedstock/pull/12 is the "right" fix.

**Comment by kmuehlbauer** [comment]
Thanks @xylar and @ocefpaf!

**Comment by amotl** [comment]
Hi there,

I was probably running into the same problems at GH-102, however I didn't investigate closer if it is exactly the same, by reading up on your conversation thoroughly.

I just wanted to inform you about it, and that I opened GH-105, in order to verify the situation again, where you may want to add corresponding fixes again, if you know how to fix this better.

With kind regards,
Andreas.

**Pull request closed without merging**
