### PR TITLE
Add extras as wetterdienst-with-* outputs

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Review by amotl — COMMENTED** [review]
Wow. Thanks Xylar. That looks like a massive influx of changes.

Me, always curious learning the Conda ecosystem, has a question about it: Is this "{package}-with-{extra}" matrix an extrapolation (and Conda package manifestation) of all "extra" slots that a PyPI package enumerates and provides?

NB: Do you need me to acknowledge this PR?

**Comment by xylar** [comment]
> Me, always curious about learning bits about the Conda ecosystem here and there, has a question about it: Is this "{package}-with-{extra}" convention an extrapolation (and Conda package manifestation) of all "extra" slots that a PyPI package enumerates and provides?

@amotl, yes, exactly.  This is at least the semi-standard way to add extras to conda-forge.  They have to be separate packages that include the "base" package as one of the dependencies.

See some examples:
https://github.com/conda-forge/airflow-feedstock/blob/main/recipe/meta.yaml#L201-L580
https://github.com/conda-forge/parsl-feedstock/blob/main/recipe/meta.yaml#L60-L289
https://github.com/conda-forge/apache-beam-feedstock/blob/main/recipe/meta.yaml#L137-L313
https://github.com/conda-forge/smart_open-feedstock/blob/2814248b302a34acf0f085e8712558d36426efbc/recipe/meta.yaml#L47-L196
https://github.com/search?q=path%3A**%2Frecipe%2Fmeta.yaml+org%3Aconda-forge+%22-with-%22&type=code&ref=advsearch

**Comment by xylar** [comment]
> NB: Do you need me to acknowledge this PR?

@amotl, @gutzbenj and @kmuehlbauer, yes I would ideally like all of you to approve this change because it's a big one.  That was my intention with https://github.com/conda-forge/wetterdienst-feedstock/pull/146#issuecomment-2531565303 above.  I used @conda-forge/wetterdienst as a shorthand for contacting all maintainers.

Similarly with https://github.com/conda-forge/admin-requests/pull/1217, it would be useful if at least one of you approves that.

**Review by amotl — APPROVED** [review]
Thanks, Xylar. Can you also acknowledge, @gutzbenj, if you agree with those improvements?

**Review by kmuehlbauer — APPROVED** [review]
If this is the recommended way of doing, I'm good with it. Thanks @xylar!

**Comment by gutzbenj** [comment]
Looks good. I wonder just if we can/shall reduce the number of extras to make this more easy to maintain?

**Comment by xylar** [comment]
@gutzbenj, that's up to you. If you compare one release with the previous one and find pyproject.toml, it's pretty easy to see what changed. So I don't find the current number of extras prohibitive.

Here's an example of what I mean.

https://github.com/earthobservations/wetterdienst/compare/v0.97.0...v0.98.0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711

**Comment by xylar** [comment]
Thanks everyone for your feedback!

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
It looks like I messed up the admin request.  Hopefully, we can get it fixed quickly.

**Comment by xylar** [comment]
Okay, the packages with the new extras are uploaded and should be available in an hour or less.

**Pull request merged**
