### PR TITLE
Fix v0.58.0 build

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
Not bumping the build number because we didn't build packages in #93

**Comment by xylar** [comment]
`stamina` still needs a recipe.

**Comment by xylar** [comment]
Adding stamina in https://github.com/conda-forge/staged-recipes/pull/23346.  Let me know if any of you also want to be maintainers.

**Comment by xylar** [comment]
@conda-forge-admin, please restart ci

**Comment by gutzbenj** [comment]
@hynek would you be interested in mainting the conda feedstock?

**Comment by xylar** [comment]
`pip check` is failing because of `pypdf2`.

**Comment by gutzbenj** [comment]
@xylar I actually just did it yesterday but that was after the release!

**Comment by xylar** [comment]
> @xylar I actually just did it yesterday but that was after the release!

Perfect!

**Pull request merged**
